name: Deploy All Lambdas via Matrix

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        function:
          - createUser
          - getUser
          - saveReminder
          - updateReminder
          - deleteReminder
          - listReminders

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install shared dependencies
      run: npm install

    - name: Zip Lambda function
      run: |
        set -e
        mkdir -p packaged
        cp ${{ matrix.function }}/index.js packaged/
        cp -r node_modules packaged/
        cd packaged
        zip -r ../${{ matrix.function }}.zip .
        cd ..
      shell: bash

    - name: Install AWS CLI
      run: |
        set -e
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install
        rm -rf awscliv2.zip aws
      shell: bash

    - name: Deploy to AWS Lambda
      run: |
        set -e
        aws lambda update-function-code \
          --function-name ${{ matrix.function }} \
          --zip-file fileb://${{ matrix.function }}.zip
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      shell: bash

    - name: Cleanup
      run: rm -rf packaged
      shell: bash
